/**
 * CSV Renderer
 * 
 * Purpose: Exports reports as CSV for analysis in Excel/spreadsheets
 * Use case: Data engineers, analysts, spreadsheet analysis
 */

import type { PlatformReport, DatasetReport, IncidentReport } from '../report-builder';


// Note: csv-stringify is a built-in Node.js style CSV generator
// We'll use a simple custom implementation instead
function stringify(data: any[][], options?: { header?: boolean; columns?: string[] }): string {
    if (!data || data.length === 0) return '';

    let result = '';

    // Add header if specified
    if (options?.header && options?.columns) {
        result += options.columns.join(',') + '\n';
    }

    // Add data rows
    for (const row of data) {
        result += row.map(cell => {
            // Escape cells containing commas, quotes, or newlines
            const cellStr = String(cell ?? '');
            if (cellStr.includes(',') || cellStr.includes('"') || cellStr.includes('\n')) {
                return `"${cellStr.replace(/"/g, '""')}"`;
            }
            return cellStr;
        }).join(',') + '\n';
    }

    return result;
}


// =====================================================
// Platform Report CSV
// =====================================================

export function renderPlatformCSV(report: PlatformReport): string {
    try {
        const sections: string[] = [];

        // Section 1: Report Metadata
        sections.push('# PLATFORM DATA QUALITY REPORT');
        sections.push('');
        sections.push(stringify([
            ['Report ID', report.metadata.reportId],
            ['Report Type', report.metadata.reportType],
            ['Report Date', report.metadata.reportDate],
            ['Generated At', report.metadata.generatedAt],
            ['Generated By', report.metadata.generatedBy],
        ]));

        // Section 2: Executive Summary
        sections.push('');
        sections.push('# EXECUTIVE SUMMARY');
        sections.push('');
        sections.push(stringify([
            ['Overall Quality Score', report.executiveSummary.overallQualityScore + '%'],
            ['Quality Status', report.executiveSummary.qualityStatus],
            ['Risk Level', report.executiveSummary.riskLevel],
        ]));

        // Section 3: Key Highlights
        sections.push('');
        sections.push('# KEY HIGHLIGHTS');
        sections.push('');
        sections.push(stringify(
            report.executiveSummary.keyHighlights.map((highlight, index) => [
                index + 1,
                highlight,
            ]),
            { header: true, columns: ['#', 'Highlight'] }
        ));

        // Section 4: Quality Metrics
        sections.push('');
        sections.push('# QUALITY METRICS');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Quality Score', report.qualityMetrics.score + '%'],
            ['Status', report.qualityMetrics.status],
            ['Trend', report.qualityMetrics.trend],
        ]));

        // Section 5: Coverage
        sections.push('');
        sections.push('# COVERAGE ANALYSIS');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Total Checks', report.coverage.totalChecks],
            ['Passed Checks', report.coverage.passedChecks],
            ['Failed Checks', report.coverage.failedChecks],
            ['Coverage Percent', report.coverage.coveragePercent + '%'],
            ['Coverage Strength', report.coverage.strength],
        ]));

        // Section 6: Risk Assessment
        sections.push('');
        sections.push('# RISK ASSESSMENT');
        sections.push('');
        sections.push(stringify([
            ['Risk Factor', 'Value'],
            ['Risk Level', report.riskAssessment.level],
            ['Open Anomalies', report.riskAssessment.openAnomalies],
            ['SLA Breaches', report.riskAssessment.slaBreaches],
            ['Critical Datasets', report.riskAssessment.criticalDatasets],
        ]));

        // Section 7: Top Failing Datasets
        if (report.topFailingDatasets.length > 0) {
            sections.push('');
            sections.push('# TOP FAILING DATASETS');
            sections.push('');
            sections.push(stringify(
                report.topFailingDatasets.map(dataset => [
                    dataset.rank,
                    dataset.dataset,
                    dataset.failedChecks,
                    dataset.qualityScore + '%',
                ]),
                {
                    header: true,
                    columns: ['Rank', 'Dataset', 'Failed Checks', 'Quality Score'],
                }
            ));
        }

        // Section 8: SLA Compliance
        sections.push('');
        sections.push('# SLA COMPLIANCE');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Compliance Percent', report.slaCompliance.compliancePercent + '%'],
            ['Breached Datasets', report.slaCompliance.breachedDatasets],
            ['Status', report.slaCompliance.status],
        ]));

        // Section 9: Observability
        sections.push('');
        sections.push('# OBSERVABILITY');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Total Assets', report.observability.totalAssets],
            ['Monitored Assets', report.observability.monitoredAssets],
            ['Monitoring Coverage', report.observability.monitoringCoverage + '%'],
            ['Last Scan Time', report.observability.lastScanTime],
        ]));

        // Section 10: Recommendations
        if (report.recommendations.length > 0) {
            sections.push('');
            sections.push('# RECOMMENDATIONS');
            sections.push('');
            sections.push(stringify(
                report.recommendations.map((rec, index) => [index + 1, rec]),
                { header: true, columns: ['#', 'Recommendation'] }
            ));
        }

        return sections.join('\n');
    } catch (error) {
        console.error('[CSV Renderer] Error rendering platform report:', error);
        throw new Error('Failed to render platform CSV report');
    }
}

// =====================================================
// Dataset Report CSV
// =====================================================

export function renderDatasetCSV(report: DatasetReport): string {
    try {
        const sections: string[] = [];

        // Section 1: Report Metadata
        sections.push('# DATASET QUALITY REPORT');
        sections.push('');
        sections.push(stringify([
            ['Report ID', report.metadata.reportId],
            ['Report Type', report.metadata.reportType],
            ['Report Date', report.metadata.reportDate],
            ['Generated At', report.metadata.generatedAt],
            ['Generated By', report.metadata.generatedBy],
        ]));

        // Section 2: Dataset Information
        sections.push('');
        sections.push('# DATASET INFORMATION');
        sections.push('');
        sections.push(stringify([
            ['Database', report.datasetInfo.database],
            ['Schema', report.datasetInfo.schema],
            ['Table', report.datasetInfo.table],
            ['Full Name', report.datasetInfo.fullName],
        ]));

        // Section 3: Quality Overview
        sections.push('');
        sections.push('# QUALITY OVERVIEW');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Quality Score', report.qualityOverview.score + '%'],
            ['Status', report.qualityOverview.status],
            ['Trend', report.qualityOverview.trend],
        ]));

        // Section 4: Checks Analysis
        sections.push('');
        sections.push('# CHECKS ANALYSIS');
        sections.push('');
        sections.push(stringify([
            ['Metric', 'Value'],
            ['Total Checks', report.checksAnalysis.total],
            ['Passed Checks', report.checksAnalysis.passed],
            ['Failed Checks', report.checksAnalysis.failed],
            ['Pass Rate', report.checksAnalysis.passRate + '%'],
        ]));
        sections.push('');
        sections.push(stringify([['Summary', report.checksAnalysis.summary]]));

        // Section 5: Failed Checks Details
        if (report.failedChecksDetails.length > 0) {
            sections.push('');
            sections.push('# FAILED CHECKS DETAILS');
            sections.push('');
            sections.push(stringify(
                report.failedChecksDetails.map(check => [
                    check.ruleName,
                    check.status,
                    check.failedRecords,
                    check.severity,
                    check.timestamp,
                ]),
                {
                    header: true,
                    columns: ['Rule Name', 'Status', 'Failed Records', 'Severity', 'Timestamp'],
                }
            ));
        }

        // Section 6: Data Freshness
        sections.push('');
        sections.push('# DATA FRESHNESS');
        sections.push('');
        sections.push(stringify([
            ['Last Updated', report.dataFreshness.lastUpdated],
            ['Freshness (Hours)', report.dataFreshness.freshnessHours],
            ['Status', report.dataFreshness.status],
        ]));

        // Section 7: Volume Metrics
        sections.push('');
        sections.push('# VOLUME METRICS');
        sections.push('');
        sections.push(stringify([
            ['Row Count', report.volumeMetrics.rowCount],
            ['Trend', report.volumeMetrics.trend],
        ]));

        // Section 8: Recommendations
        if (report.recommendations.length > 0) {
            sections.push('');
            sections.push('# RECOMMENDATIONS');
            sections.push('');
            sections.push(stringify(
                report.recommendations.map((rec, index) => [index + 1, rec]),
                { header: true, columns: ['#', 'Recommendation'] }
            ));
        }

        return sections.join('\n');
    } catch (error) {
        console.error('[CSV Renderer] Error rendering dataset report:', error);
        throw new Error('Failed to render dataset CSV report');
    }
}

// =====================================================
// Incident Report CSV
// =====================================================

export function renderIncidentCSV(report: IncidentReport): string {
    try {
        const sections: string[] = [];

        // Section 1: Report Metadata
        sections.push('# INCIDENT REPORT');
        sections.push('');
        sections.push(stringify([
            ['Report ID', report.metadata.reportId],
            ['Incident ID', report.incidentOverview.incidentId],
            ['Generated At', report.metadata.generatedAt],
            ['Generated By', report.metadata.generatedBy],
        ]));

        // Section 2: Incident Overview
        sections.push('');
        sections.push('# INCIDENT OVERVIEW');
        sections.push('');
        sections.push(stringify([
            ['Trigger Reason', report.incidentOverview.triggerReason],
            ['Severity', report.incidentOverview.severity],
            ['Status', report.incidentOverview.status],
        ]));

        // Section 3: Impact
        sections.push('');
        sections.push('# IMPACT ANALYSIS');
        sections.push('');
        sections.push(stringify([['Total Impact', report.impact.totalImpact]]));

        if (report.impact.impactedDatasets.length > 0) {
            sections.push('');
            sections.push('# IMPACTED DATASETS');
            sections.push('');
            sections.push(stringify(
                report.impact.impactedDatasets.map(dataset => [
                    dataset.dataset,
                    dataset.impact,
                ]),
                { header: true, columns: ['Dataset', 'Impact'] }
            ));
        }

        // Section 4: Timeline
        sections.push('');
        sections.push('# TIMELINE');
        sections.push('');
        sections.push(stringify(
            report.timeline.map(event => [
                event.timestamp,
                event.event,
                event.details,
            ]),
            { header: true, columns: ['Timestamp', 'Event', 'Details'] }
        ));

        // Section 5: Root Cause Analysis
        sections.push('');
        sections.push('# ROOT CAUSE ANALYSIS');
        sections.push('');
        sections.push(stringify([['Confidence', report.rootCauseAnalysis.confidence]]));
        sections.push('');
        sections.push(stringify(
            report.rootCauseAnalysis.hints.map((hint, index) => [index + 1, hint]),
            { header: true, columns: ['#', 'Hint'] }
        ));

        // Section 6: Resolution
        sections.push('');
        sections.push('# RESOLUTION');
        sections.push('');
        sections.push(stringify([['Status', report.resolution.status]]));
        sections.push('');
        sections.push(stringify(
            report.resolution.actionItems.map((item, index) => [index + 1, item]),
            { header: true, columns: ['#', 'Action Item'] }
        ));

        return sections.join('\n');
    } catch (error) {
        console.error('[CSV Renderer] Error rendering incident report:', error);
        throw new Error('Failed to render incident CSV report');
    }
}

// =====================================================
// Generic CSV Renderer
// =====================================================

export function renderCSV(
    report: PlatformReport | DatasetReport | IncidentReport
): string {
    const reportType = report.metadata.reportType;

    switch (reportType) {
        case 'PLATFORM':
            return renderPlatformCSV(report as PlatformReport);
        case 'DATASET':
            return renderDatasetCSV(report as DatasetReport);
        case 'INCIDENT':
            return renderIncidentCSV(report as IncidentReport);
        default:
            throw new Error(`Unsupported report type: ${reportType}`);
    }
}
