-- Governance Module Tables
-- Run this in Snowflake to enable Data Governance features

USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DQ_CONFIG;

-- 1. Data Ownership
-- Links datasets to owners and stewards
CREATE TABLE IF NOT EXISTS DQ_DATASET_OWNERSHIP (
    OWNERSHIP_ID VARCHAR(36) DEFAULT UUID_STRING(),
    DATASET_NAME VARCHAR(200) NOT NULL, -- Logical link to source table
    SCHEMA_NAME VARCHAR(100) NOT NULL,
    DATABASE_NAME VARCHAR(100) NOT NULL,
    DATA_OWNER VARCHAR(100),
    DATA_STEWARD VARCHAR(100),
    CRITICALITY VARCHAR(20), -- 'HIGH', 'MEDIUM', 'LOW'
    CONTACT_EMAIL VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, DATASET_NAME)
);

-- 2. SLA Configuration
-- Defines expectations for datasets
CREATE TABLE IF NOT EXISTS DQ_SLA_CONFIG (
    SLA_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    DATASET_NAME VARCHAR(200),
    SCHEMA_NAME VARCHAR(100),
    DATABASE_NAME VARCHAR(100),
    SLA_TYPE VARCHAR(50), -- 'FRESHNESS', 'QUALITY', 'AVAILABILITY'
    THRESHOLD_VALUE VARCHAR(50),
    WINDOW_HOURS INT,
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100)
);

-- 3. Governance Policies
-- Organization-wide policies
CREATE TABLE IF NOT EXISTS DQ_GOVERNANCE_POLICIES (
    POLICY_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    POLICY_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    SCOPE VARCHAR(100), -- 'GLOBAL', 'PII', 'FINANCE'
    IS_ENFORCED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Audit Log
-- Tracks all governance changes
CREATE TABLE IF NOT EXISTS DQ_GOVERNANCE_AUDIT (
    AUDIT_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    ENTITY_TYPE VARCHAR(50), -- 'OWNERSHIP', 'SLA', 'POLICY'
    ENTITY_ID VARCHAR(36),
    ACTION VARCHAR(50), -- 'CREATE', 'UPDATE', 'DELETE'
    CHANGED_BY VARCHAR(100),
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    OLD_VALUE VARIANT,
    NEW_VALUE VARIANT
);

-- Seed Initial Policies
INSERT INTO DQ_GOVERNANCE_POLICIES (POLICY_NAME, DESCRIPTION, SCOPE, IS_ENFORCED)
SELECT 'PII Data Masking', 'All Personally Identifiable Information must be masked in lower environments.', 'GLOBAL', TRUE
WHERE NOT EXISTS (SELECT 1 FROM DQ_GOVERNANCE_POLICIES WHERE POLICY_NAME = 'PII Data Masking');

INSERT INTO DQ_GOVERNANCE_POLICIES (POLICY_NAME, DESCRIPTION, SCOPE, IS_ENFORCED)
SELECT 'Bronze Layer Retention', 'Raw data in Bronze layer must be retained for 7 years.', 'COMPLIANCE', FALSE
WHERE NOT EXISTS (SELECT 1 FROM DQ_GOVERNANCE_POLICIES WHERE POLICY_NAME = 'Bronze Layer Retention');
