/**
 * API Endpoint: Get Evidence
 * POST /api/antigravity/get-evidence
 * 
 * Executes a guided question using AI-generated SQL.
 * SQL is generated by Gemini after reading the schema - NOT hardcoded.
 */

import { NextRequest, NextResponse } from 'next/server';
import { executeQuestion, getQuestionsForType } from '@/lib/antigravity/investigation-controller';
import { getChartConfig, transformDataForChart } from '@/lib/antigravity/chart-intent-mapper';
import { getServerConfig } from '@/lib/server-config';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { sessionId, database, schema, table, questionKey, insightType } = body;

        if (!database || !schema || !table || !questionKey) {
            return NextResponse.json(
                { success: false, error: 'Missing required parameters' },
                { status: 400 }
            );
        }

        const config = getServerConfig();
        if (!config) {
            return NextResponse.json(
                { success: false, error: 'No Snowflake connection available' },
                { status: 401 }
            );
        }

        const assetId = `${database.toUpperCase()}.${schema.toUpperCase()}.${table.toUpperCase()}`;

        // Get question label for AI generation
        const questions = getQuestionsForType(insightType || 'QUALITY');
        const question = questions.find(q => q.key === questionKey);
        const questionLabel = question?.label || questionKey;

        // Execute question with AI-generated SQL
        const result = await executeQuestion(
            sessionId || 'anonymous',
            assetId,
            questionKey,
            questionLabel,
            insightType || 'QUALITY'
        );

        // Check for validation errors
        if (result.validationErrors.length > 0) {
            return NextResponse.json({
                success: true,
                data: {
                    questionKey,
                    sql: result.sql,
                    sqlGenerated: result.sqlGenerated,
                    chart: {
                        type: result.chartType,
                        title: questionLabel,
                        data: [],
                    },
                    validationErrors: result.validationErrors,
                    rowCount: 0,
                },
            });
        }

        // Get chart configuration
        const chartConfig = getChartConfig(questionKey);

        // Transform data for chart rendering
        const { chartData, xKey, yKey } = transformDataForChart(result.data, chartConfig);

        return NextResponse.json({
            success: true,
            data: {
                questionKey,
                sql: result.sql,
                sqlGenerated: result.sqlGenerated,
                chart: {
                    type: chartConfig.type,
                    title: chartConfig.title,
                    color: chartConfig.color,
                    xAxis: xKey,
                    yAxis: yKey,
                    threshold: chartConfig.threshold,
                    data: chartData,
                },
                rawData: result.data,
                rowCount: result.data.length,
                validationErrors: [],
            },
        });
    } catch (error: any) {
        console.error('[INVESTIGATION] Error getting evidence:', error);
        return NextResponse.json(
            { success: false, error: error.message || 'Failed to get evidence' },
            { status: 500 }
        );
    }
}
